### ISSUE TITLE
Using meta-bind-button

### ISSUE THREAD

**Issue by stefano-HH** [matthewturk/obsidian-sidecar-panel#11]
Hi,
I would like to integrate a button into a sidecar file.
The simple example works directly in the note, but not in the sidecar file...
Have I forgotten something?
Or is it a bug?

Maybe someone can nudge me in the right direction...

many thanks in advance

```
```meta-bind-button
label: download images
icon: ""
style: default
class: ""
cssStyle: ""
backgroundImage: ""
tooltip: ""
id: ""
hidden: false
actions:
  - type: command
    command: editor:download-attachments
```
```

**Comment by matthewturk** [comment]
Oh, interesting! I'll check it out. There may have been an API change I
missed.

**Comment by matthewturk** [comment]
I haven't yet been able to make this occur as expected, but I'm trying.  I was able to verify that it works for some types of buttons.  For example, given this file `button-panel.md`:

````
```meta-bind-button
label: increment
icon: ""
style: default
class: ""
cssStyle: ""
backgroundImage: ""
tooltip: ""
id: ""
hidden: false
actions:
  - type: updateMetadata
    bindTarget: count
    evaluate: true
    value: "x + 1"
```
````

And then this in another note:

````
---
sidecar-panel: button-panel
count: 0
---
````

I am able to use the button as expected from the panel.  In that case, it's using the built-in `updateMetadata` command for meta-bind.

**However**, it's also the case that swapping it to include:

````
```meta-bind-button
label: reveal
icon: ""
style: default
class: ""
cssStyle: ""
backgroundImage: ""
tooltip: ""
id: ""
hidden: false
actions:
  - type: command
    command: file-explorer:reveal-active-file
```
````

now no longer functions.  My guess is that there is a context that is not being passed down during this process, and I'm going to try to dig in to see what it is and if I can address it.  (I believe the same will apply to `editor:download-attachments`.)
